name: Analyze Branch

# then define on which event, here a push
on:
  push:
    branches:
      - dev
      - staging
      - production
      - master

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Run Tests 
        run: npm run test:ci
      - name: Run List 
        run: npm run lint:ci