name: Analyze Branch

# then define on which event, here a push
on:
  push:
    branches:
      - dev
      - staging
      - production
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.REF }}
          fetch-depth: 0
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        id: extract_branch
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: ${{ github.event.repository.name }}
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install packages
        run: npm ci
      - name: Run Tests 
        run: npm run test
      - name: Run List 
        run: npm run lint
      - name: Analize Analyze with SonarQube 
        run: sonar-scanner \
  -Dsonar.projectKey=pdp-store-next \
  -Dsonar.sources=. \
  -Dsonar.host.url=http://159.223.6.29:9000 \
  -Dsonar.login=bd7000c40b17d9b4d6f9ddb1944974a7ed6b2aca