name: GitHub Actions Demo
on:
  pull_request:
    branches:
      - master
jobs:
  file_existence:
    steps:
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "package.json, CHANGELOG.md, README.md"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: echo All files exists!
    changelog_unchanged:
    - all: ["!CHANGELOG.md"]